# Generated by Django 4.2.7 on 2023-11-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject_Model',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=250)),
                ('status', models.CharField(default='Available', editable=False, max_length=20)),
            ],
            options={
                'db_table': 'subject',
            },
        ),
    ]
