# Generated by Django 4.2.7 on 2023-11-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=250)),
                ('mobile', models.CharField(max_length=10)),
                ('mail', models.CharField(max_length=250)),
                ('experience', models.CharField(max_length=250)),
                ('staff_status', models.CharField(default='Available', editable=False, max_length=20)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
    ]
